spring:
  datasource:
    url: jdbc:h2:file:/data/musaladb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    open-in-view: true
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate.ddl-auto: create-drop
  h2:
    console:
      enabled: true

logging:
  file:
    name: logs/application-debug.log
  pattern:
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    com.example.musala.scheduler: INFO